name = input("Your name? ")
email = input("Your email: ")
age = int(input("Your age: "))
height = float(input("Your height: "))
is_active_input = input("Do you want to receive notifications from the site? (yes/no): ").strip().lower()
is_active = is_active_input == "yes"
print("\nSummary of entered information:")
print(f"Name: {name}")
print(f"Email: {email}")
print(f"Age: {age}")
print(f"Height: {height}")
print(f"Active status for notifications: {is_active}")